name: Build Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Google Cloud Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
          install_components: beta
      - name: Set Docker image tag
        id: set-docker-tag
        run: |
          sha_short=$(git rev-parse --short HEAD)
          tag=gcr.io/hoprassociation/hopr-admin:${sha_short}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Build Docker image locally
        run: docker build -t ${{ steps.set-docker-tag.outputs.tag }} .
      - name: Push Docker image to gcr.io
        run: docker push ${{ steps.set-docker-tag.outputs.tag }}


